blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/khulnasoft/titanrepo/discussions
    about: Ask questions and discuss ideas with other community members
