name: JS Package Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      TITAN_TOKEN: ${{ secrets.TITAN_TOKEN }}
      TITAN_TEAM: ${{ secrets.TITAN_TEAM }}
      TITAN_REMOTE_ONLY: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-go
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - run: |
          pnpm -- titan run test  --filter=...[${{ github.event.pull_request.base.sha }}] --filter=!cli --color
